version: '2.1'
 
services:
  openmrs-referenceapplication-mysql:
    restart: "always"
    image: mysql:5.6
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      MYSQL_USER: ${MYSQL_USER:-openmrs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
    healthcheck:
      test: "exit 0"
    volumes:
      - ./db:/var/lib/mysql
      - ./dbdump:/docker-entrypoint-initdb.d
      #- /my/custom:/etc/mysql/conf.d #if you want custom mysql configurations uncomment and create conf folder
 
  openmrs-referenceapplication:
    restart: "always"
    image: openmrs/openmrs-reference-application-distro:latest
    depends_on:
      - openmrs-referenceapplication-mysql
    ports:
      - "8090:8080"
    environment:
      DB_DATABASE: ${MYSQL_DB:-openmrs}
      DB_HOST: openmrs-referenceapplication-mysql
      DB_USERNAME: ${MYSQL_USER:-openmrs}
      DB_PASSWORD: ${MYSQL_PASSWORD:-Admin123}
#      DB_CREATE_TABLES: 'true'
#      DB_AUTO_UPDATE: 'true'
#      MODULE_WEB_ADMIN: 'true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs/"]
      timeout: 20s
    volumes:
      - ./openmrs-referenceapplication-data:/usr/local/tomcat/.OpenMRS/
      - ./modules:/usr/local/tomcat/.OpenMRS/modules/ # do not store modules in data
  #   - /usr/local/tomcat/.OpenMRS/owa/ # do not store owa in data
 
#volumes:
#   openmrs-referenceapplication-mysql-data:
#   openmrs-referenceapplication-data:
